### ISSUE TITLE
Suggest remove link icon from repo default reedmen

### ISSUE THREAD

**Issue by gawmen** [WyomingSoftware/git-mobile-for-github#3]
The GitHub link icon appears before the heading markers on the default ready for repos.  This has no value in that it works only in browser to bring the heading to the top of the page.  In the app this cannot happen. Perhaps filter it out before display.

![screen shot 2016-04-22 at 8 50 51 am](https://cloud.githubusercontent.com/assets/18506485/14745180/61f11324-0867-11e6-934b-37f07a4ca723.png)

**Comment by wyoming** [comment]
This anchor seems to be embedded firmly into the HTMl. It will produce an error when tapped but the error is not critical. Th app swallows it. Removing the anchors would be more than difficult. They are just useless anchors. Suggest we let this one go.
