### ISSUE TITLE
Repo search by owner/name fails with incomplete string

### ISSUE THREAD

**Issue by wkande** [WyomingSoftware/git-mobile-for-github#9]
Works
git repo:wyomingsoftware/git-mobile-for-github

Fails
git repo:wyomingsoftware

![screen shot 2016-07-11 at 6 48 26 am](https://cloud.githubusercontent.com/assets/3522283/16731087/8f71f39e-4733-11e6-86d8-44d9036f3c5f.png)

**Comment by paul-styles** [comment]
The API returns a 422 error for searches that request a resource that does not exist or for which the user has no permissions to view. Added a trap in the buildError function of the httpProvider to produce a more user friendly message.
